/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART_log.h"
#include "ADC.h"
#include "INT_ADC.h"
#include "ADC_in_aliases.h"
#include "ADC_in.h"
#include "Power_LED_aliases.h"
#include "Power_LED.h"
#include "LED_Yellow_aliases.h"
#include "LED_Yellow.h"
#include "LED_Green_aliases.h"
#include "LED_Green.h"
#include "LED_Red_aliases.h"
#include "LED_Red.h"
#include "PushButton_aliases.h"
#include "PushButton.h"
#include "isr_pushbutton1.h"
#include "Pin_1_aliases.h"
#include "Pin_1.h"
#include "isr_pushbutton.h"
#include "isr_UART.h"
#include "DAC.h"
#include "Pin_2_aliases.h"
#include "Pin_2.h"
#include "UART_log_IntClock.h"
#include "ADC_AMux.h"
#include "ADC_Ext_CP_Clk.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "DAC_DacClk.h"
#include "DAC_Wave1_DMA_dma.h"
#include "DAC_Wave2_DMA_dma.h"
#include "DAC_VDAC8.h"
#include "DAC_BuffAmp.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

